services:
  - type: web
    name: sm-downloader-backend
    runtime: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python scripts/api_server.py"
    plan: free
